name: Lint pull request title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Lint pull request title
        uses: morrisoncole/pr-lint-action@v1.7.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          title-regex: '^(build|chore|ci|docs|feat|fix|perf|refactor|release|revert|style|test)(\((.*?)\))?: .{1,140}$'
          on-failed-regex-fail-action: true
          on-failed-regex-request-changes: true
          on-failed-regex-comment: |
            Your pull request title should follow the conventional commit pattern: `%regex%`!

            The conventional commit pattern consists of a type, an optional scope, and a description:

            - build: Changes that affect the build system or external dependencies
            - chore: Other changes that don't modify src or test files
            - ci: Changes to our CI configuration files and scripts
            - docs: Documentation only changes
            - feat: A new feature
            - fix: A bug fix
            - perf: A code change that improves performance
            - refactor: A code change that neither fixes a bug nor adds a feature
            - revert: Reverts a previous commit
            - style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
            - test: Adding missing tests or correcting existing tests

            Please ensure your pull request title starts with one of these types and follows the pattern specified above.
