name: Merge dev into production after release

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      ga_token:
        required: true

jobs:
  fast-forward-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ga_token }}

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Merge specified branch into main
        run: |
          git checkout production
          git merge --no-ff dev
          git push origin production
        env:
          GITHUB_TOKEN: ${{ secrets.ga_token }}
