name: Build npm ⚙️

on: workflow_call

jobs:
  build-and-commit:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node: ["22"]
    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          fetch-depth: 0 # Necessary to fetch all history for branch and tags

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run test --if-present

      - name: Build assets
        run: npm run build --if-present

      - name: Configure Git
        if: github.head_ref != ''
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and push built assets
        if: github.head_ref != ''
        run: |
          git checkout -B build-assets
          git add -A -f -- assets/dist/
          git diff --staged --quiet || {
            git commit -m "chore: build assets [skip ci]"
            git push origin build-assets:${{ github.head_ref }}
          }
