name: Build npm ⚙️

on: workflow_call

jobs:
  build-and-commit:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [ '18' ]
    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessary to fetch all history for branch and tags
          ref: ${{ github.head_ref }}  # Checkout the head of the PR

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run test --if-present
