name: 🤖 Prepare for Release 🚀

on:
  workflow_call:
    secrets:
      ga_token:
        required: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.ga_token }}
      - name: Set Environment Variables
        if: ${{ steps.release.outputs.release_created }}
        run: |
          echo "GITHUB_REPO_SLUG=$(basename $GITHUB_WORKSPACE)" >> $GITHUB_ENV
          echo "GITHUB_TAG=${{ steps.release.outputs.tag_name }}" >> $GITHUB_ENV
      - name: Prepare artifact
        if: ${{ steps.release.outputs.release_created }}
        run: |
          export COMPOSER_MEMORY_LIMIT=-1
          export GITHUB_BUILD_PATH=${{ github.workspace }}
          echo "File to be created : $GITHUB_BUILD_PATH/$GITHUB_REPO_SLUG-$GITHUB_TAG.zip"
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          mv wp-cli.phar /usr/local/bin/wp
          wp package install wp-cli/dist-archive-command
          npm install
          npm run build
          composer install --no-dev --optimize-autoloader
          cd ..
          wp dist-archive $GITHUB_REPO_SLUG $GITHUB_BUILD_PATH/$GITHUB_REPO_SLUG-$GITHUB_TAG.zip
          cd $GITHUB_BUILD_PATH
          ls $GITHUB_BUILD_PATH
      - name: Upload release artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.ga_token }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ${{github.workspace}}/$GITHUB_REPO_SLUG-$GITHUB_TAG.zip --clobber
      - name: Check if an after release workflow file exists
        id: checkfile
        run: |
          echo "Checking for the file..."
          if [ -f .github/workflows/after-release.yml ]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi
      - name: Update production branch
        if: ${{ steps.release.outputs.release_created }} && ${{ steps.checkfile.outputs.exists == 'true' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "after-release.yml"
          token: ${{ secrets.ga_token }}
