name: Append MO Files 🌐

on: workflow_call

jobs:
  update-mo-files:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: wp-cli/wp-cli-bundle

      - name: Generate .mo files from .po files
        run: wp i18n make-mo languages

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and push .mo files
        run: |
          git add -A
          git diff --staged --quiet || {
                git commit --amend --no-edit
                git push origin ${{ github.head_ref }} --force-with-lease
            }
