name: Update MO Files 🌐

on: workflow_call

jobs:
  update-mo-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: wp-cli/wp-cli-bundle

      - name: Generate .mo files from .po files
        run: wp i18n make-mo languages

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create and push new branch for MO update
        run: |
          git checkout -b l10n/update-mo-${{ github.run_id }}
          git add languages/
          
          if ! git diff --staged --quiet; then
            git commit -m "chore(l10n): update .mo files"
            git push origin l10n/update-mo-${{ github.run_id }}
          else
            echo "No changes detected in .mo files, skipping commit."
            exit 0
          fi

      - name: Create Pull Request for MO Updates
        run: |
          gh pr create --title "chore(l10n): update .mo files" \
            --body "Automated update of .mo files" \
            --base ${{ github.head_ref }} \
            --head l10n/update-mo-${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}